#!/usr/bin/env python3
"""Materialise tmux format chains for per-command icons.

Reads tools/icons.map plus nvim-web-devicons, writes icons.conf. Nothing here
runs at tmux runtime: the output is plain formats with no #() in it.

Usage: tools/gen-icons.py [--offline]
"""
import re, sys, pathlib, urllib.request

ROOT = pathlib.Path(__file__).resolve().parent.parent
CACHE = ROOT / "tools" / ".devicons-cache.lua"
SOURCES = [
    "https://raw.githubusercontent.com/nvim-tree/nvim-web-devicons/master/"
    "lua/nvim-web-devicons/default/icons_by_file_extension.lua",
    "https://raw.githubusercontent.com/nvim-tree/nvim-web-devicons/master/"
    "lua/nvim-web-devicons/default/icons_by_filename.lua",
]

# Claude's process name is its version number, so it is matched by pattern.
CLAUDE_ICON, CLAUDE_COLOR = "✳", "#d97757"
FALLBACK_ICON, FALLBACK_COLOR = "\U000f0489", "$tn_fg"


def fetch() -> str:
    if "--offline" in sys.argv:
        return CACHE.read_text()
    body = ""
    for url in SOURCES:
        with urllib.request.urlopen(url, timeout=30) as r:
            body += r.read().decode()
    CACHE.write_text(body)
    return body


def parse_db(text):
    pat = re.compile(
        r'\["([^"]+)"\]\s*=\s*\{\s*icon\s*=\s*"([^"]+)",\s*color\s*=\s*"(#[0-9A-Fa-f]{6})"'
    )
    return {m[1]: (m[2], m[3].lower()) for m in pat.finditer(text)}


def read_map():
    rows = []
    for line in (ROOT / "tools" / "icons.map").read_text().splitlines():
        line = line.split("#", 1)[0].strip() if not line.lstrip().startswith("#") else ""
        if not line:
            continue
        parts = line.split()
        rows.append((parts[0], parts[1], parts[2] if len(parts) > 2 else None))
    return rows


def chain(entries, value_of, inner):
    """Build #{?cond,a,b} nesting. Commas inside a branch must be escaped as #,."""
    out = inner
    for cmd, val in reversed(entries):
        out = "#{?#{==:$tn_cmd,%s},%s,%s}" % (cmd, value_of(val), out)
    return out


def main():
    db = parse_db(fetch())
    rows, icons, colors, missing = read_map(), [], [], []

    for cmd, key, override in rows:
        if key.startswith("="):          # literal glyph, for tools devicons lacks
            icons.append((cmd, key[1:]))
            colors.append((cmd, override or FALLBACK_COLOR))
            continue
        if key not in db:
            missing.append((cmd, key))
            continue
        glyph, color = db[key]
        icons.append((cmd, glyph))
        colors.append((cmd, override or color))

    icon_chain = "#{?$tn_is_claude,%s,%s}" % (
        CLAUDE_ICON, chain(icons, lambda v: v, FALLBACK_ICON))
    color_chain = "#{?$tn_is_claude,%s,%s}" % (
        CLAUDE_COLOR, chain(colors, lambda v: v, FALLBACK_COLOR))

    header = (
        "# GENERATED by tools/gen-icons.py -- do not edit.\n"
        "#\n"
        "# Source: tools/icons.map + nvim-web-devicons. Regenerate after editing\n"
        "# the map. Runtime cost is zero: these are plain formats, no #() shells.\n"
        f"# {len(icons)} commands mapped.\n\n"
        "# $tn_cmd and $tn_is_claude must already be defined by the caller.\n"
    )
    (ROOT / "icons.conf").write_text(
        f'{header}tn_icon="{icon_chain}"\ntn_icon_fg="{color_chain}"\n')

    print(f"icons.conf: {len(icons)} comandos")
    for cmd, key in missing:
        print(f"  sem entrada: {cmd} -> {key}", file=sys.stderr)


if __name__ == "__main__":
    main()
